import artistImg from "../../../assets/img/artistImg.png";

export const artistData = {
  filtersArr: [
    { label: "Recently Added", value: "recentlyAdded" },
    { label: "Female", value: "female" },
    { label: "Male", value: "male" },
    { label: "Most Popular", value: "mostPopular" },
  ],
  artistsArr: [
    { name: "skrillex", imgSrc: artistImg },
    {
      name: "skrillex",
      imgSrc: artistImg,
      isAvaible: true,
      city: "london",
      country: "uk",
      skills: "singer, songwriter",
    },
    { name: "skrillex", imgSrc: artistImg },
    { name: "skrillex", imgSrc: artistImg },
    { name: "skrillex", imgSrc: artistImg },
    { name: "skrillex", imgSrc: artistImg },
    { name: "skrillex", imgSrc: artistImg },
    { name: "skrillex", imgSrc: artistImg },
    { name: "skrillex", imgSrc: artistImg },
    { name: "skrillex", imgSrc: artistImg },
  ],
};

export const filterResults = [
  {
    name: "skrillex",
    imgSrc: artistImg,

    city: "london",
    country: "uk",
    singersCollab: "justin beiber, kid laroi",
    workingSkill: "mixer",
  },
  {
    name: "skrillex",
    imgSrc: artistImg,
    isAvaible: true,
    city: "london",
    country: "uk",
    singersCollab: "justin beiber, kid laroi",
    workingSkill: "mixer",
  },
  {
    name: "skrillex",
    imgSrc: artistImg,

    city: "london",
    country: "uk",
    singersCollab: "justin beiber, kid laroi",
    workingSkill: "mixer",
  },
  {
    name: "skrillex",
    imgSrc: artistImg,

    city: "london",
    country: "uk",
    singersCollab: "justin beiber, kid laroi",
    workingSkill: "mixer",
  },
  {
    name: "skrillex",
    imgSrc: artistImg,
    isAvaible: true,
    city: "london",
    country: "uk",
    singersCollab: "justin beiber, kid laroi",
    workingSkill: "mixer",
  },
  {
    name: "skrillex",
    imgSrc: artistImg,
    isAvaible: true,
    city: "london",
    country: "uk",
    singersCollab: "justin beiber, kid laroi",
    workingSkill: "mixer",
  },
  {
    name: "skrillex",
    imgSrc: artistImg,
    isAvaible: true,
    city: "london",
    country: "uk",
    singersCollab: "justin beiber, kid laroi",
    workingSkill: "mixer",
  },
  {
    name: "skrillex",
    imgSrc: artistImg,
    isAvaible: true,
    city: "london",
    country: "uk",
    singersCollab: "justin beiber, kid laroi",
    workingSkill: "mixer",
  },
  {
    name: "skrillex",
    imgSrc: artistImg,
    isAvaible: true,
    city: "london",
    country: "uk",
    singersCollab: "justin beiber, kid laroi",
    workingSkill: "mixer",
  },
  {
    name: "skrillex",
    imgSrc: artistImg,
    isAvaible: true,
    city: "london",
    country: "uk",
    singersCollab: "justin beiber, kid laroi",
    workingSkill: "mixer",
  },
  {
    name: "skrillex",
    imgSrc: artistImg,
    isAvaible: true,
    city: "london",
    country: "uk",
    singersCollab: "justin beiber, kid laroi",
    workingSkill: "mixer",
  },
  {
    name: "skrillex",
    imgSrc: artistImg,
    isAvaible: true,
    city: "london",
    country: "uk",
    singersCollab: "justin beiber, kid laroi",
    workingSkill: "mixer",
  },
  {
    name: "skrillex",
    imgSrc: artistImg,
    isAvaible: true,
    city: "london",
    country: "uk",
    singersCollab: "justin beiber, kid laroi",
    workingSkill: "mixer",
  },
  {
    name: "skrillex",
    imgSrc: artistImg,
    isAvaible: true,
    city: "london",
    country: "uk",
    singersCollab: "justin beiber, kid laroi",
    workingSkill: "mixer",
  },
  {
    name: "skrillex",
    imgSrc: artistImg,

    city: "london",
    country: "uk",
    singersCollab: "justin beiber, kid laroi",
    workingSkill: "mixer",
  },
  {
    name: "skrillex",
    imgSrc: artistImg,
    city: "london",
    country: "uk",
    singersCollab: "justin beiber, kid laroi",
    workingSkill: "mixer",
  },
];
